spring:
  application:
    name: notification-service

  datasource:
    url: ${DB_URL}
    username: ${DB_UNAME}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    show-sql: true

  messages:
    basename: messages


app:
  notification:
    channel-type:
      sms:
        content-length: ${SMS_LENGTH}
      push:
        content-length: ${PUSH_LENGTH}